### ISSUE TITLE
Nightwatch.js results don't show on visualisation

### ISSUE THREAD

**Issue by ghost** [bbc/ShouldIT#20]
Hi,

I'm hoping you can help me. I'm using [Nightwatch.js](http://nightwatchjs.org/) as my test runner and can't find a way for ShouldIT to read the default `.xml` result files generated when my tests have completed.

Can you reccomend a package (or solution) I could use in order for ShouldIT to interpret the results to allow for me to use the visual interface as expected.

Please see a results file below for reference:
```
<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="7">

  <testsuite name="chat.passiveState.openPassiveState.test"
    errors="0" failures="1" hostname="" id="" package="passiveState" skipped="4"
    tests="7" time="34.54" timestamp="Tue, 16 May 2017 13:28:01 GMT">
  
    <testcase name="it should show the avatars of the agents available to chat" classname="chat.passiveState.openPassiveState.test" time="5.388" assertions="4">

    

    

    

    
    </testcase>
  
    <testcase name="it should show the correct direct price and ota prices for various scenarios" classname="chat.passiveState.openPassiveState.test" time="6.593" assertions="4">

    

    

    

    
    </testcase>
  
    <testcase name="it should refresh the displayed prices when prompted" classname="chat.passiveState.openPassiveState.test" time="34.54" assertions="5">

    

    

    

      <failure message="Timed out while waiting for element &lt;[data-qa-tag=message]&gt; to be present for 30000 milliseconds.">    at Object.it should refresh the displayed prices when prompted (/Users/gavin/Code/triptease/test-drive/e2e/guestPa/tests/chat/passiveState/openPassiveState.test.js:21:8)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)</failure>

    
    </testcase>
  
  
    
    <testcase
      name="it should show an x button to close the conversation" classname="chat.passiveState.openPassiveState.test">
      <skipped />
    </testcase>
    
    <testcase
      name="it should show a text field for the user to enter their message" classname="chat.passiveState.openPassiveState.test">
      <skipped />
    </testcase>
    
    <testcase
      name="it should show a message from the hotel" classname="chat.passiveState.openPassiveState.test">
      <skipped />
    </testcase>
    
    <testcase
      name="it should show a message prompting the user type a message in the text field" classname="chat.passiveState.openPassiveState.test">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
```
Many thanks!

**Comment by mackstar** [comment]
Hi Gavin,

I will look into this over the weekend!

Cheers

**Comment by ghost** [comment]
Awesome, thank you so much!

**Comment by ghost** [comment]
Hi @mackstar, have you had a chance to take a look at this at all?

Many thanks!
